baseURL = "https://example.com"
languageCode = "zh-CN"
title = "Dawn's vlog | Personal "
theme = "LeaveIt"

paginate = 10
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "博文"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "关于我"
    url = "/about/"
    weight = 4

[params]
    since = 2020
    author = "Dawn"                           # Author's name
    avatar = "/images/me/avatar.jpg"           # Author's avatar
    subtitle = "理想主义者"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "posts" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords
    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'
    enableGitalk = true

[params.social]
    GitHub = "Dawn666Y"
    # Twitter = "xxoo"
    Email   = "yvlm666@outlook.com"
    # Instagram = "xxoo"
    # Wechat = "/images/me/wechat.png"  # Wechat QRcode image
    # Facebook = "xxoo"
    Telegram = "Dawn666"
    # Dribbble = "xxoo"
    # Medium = "xxoo"
    
[params.gitalk] 
    clientID = "e2ea845ea908ffb0be8b" # Your client ID
    clientSecret = "0f908d99403a9c45b6e64847b03072d4b9ecd654" # Your client secret
    repo = "dawn666y.github.io" # The repo to store comments
    owner = "Dawn666Y" # Your GitHub ID
    admin= "Dawn666Y" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 10 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.

# 自定义目录toc
toc = true                # 是否开启目录
autoCollapseToc = true   # Auto expand and collapse toc